title: Basecamp CSS
email: ryan@takenot.es
description: "Basecamp in a minimally opinionated CSS Framework. It's basically just a column grid system with typesizes, responsive images, and spacing."
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  takenot-es

# Build settings
plugins:
  - jekyll-feed


sass:
  sass_dir: "/assets/sass/theme/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
